### ISSUE TITLE
Use of unresolved Identifier

### ISSUE THREAD

**Issue by talkaboutdesign** [Constantine-Fry/das-quadrat#19] opened 2015-01-14 20:57 UTC
Followed directions on linking framework with my project. 

In app delegate getting the following errors: 

"Use of unresolved identifier 'Client'" 
same for Configuration and Session

Any advice?

**Comment by Constantine-Fry** [comment] 2015-01-15 06:18
Is you project ObjC or Swift only?

**Comment by talkaboutdesign** [comment] 2015-01-15 11:07
Swift + a few libraries in Obj-C. So it has a bridging header file.

**Comment by Constantine-Fry** [comment] 2015-01-16 09:58
What is you deployment target?

**Comment by talkaboutdesign** [comment] 2015-01-16 17:53
8.0

**Comment by Constantine-Fry** [comment] 2015-01-17 08:09
hmm, did you import the framework?
```
import QuadratTouch
```

**Comment by Constantine-Fry** [comment] 2015-01-25 17:44
I'm gonna close the issue. Let me know if you still have any problems.

**Comment by talkaboutdesign** [comment] 2015-01-28 17:31
Problem persists. Yes framework was imported. I tried it a few times following your documentation.

**Comment by Constantine-Fry** [comment] 2015-01-28 18:08
Gat you reproduce tho problem in separate project and send this project to me?

**Comment by Constantine-Fry** [comment] 2015-02-07 09:47
Maybe the problem is that your project's deployment target is iOS 7.0. Embedded frameworks not supported on iOS 7.x. You can try to add source code files of framework directly into your project.

**Closed** 2015-04-09 19:46 UTC

**Comment by rawanOmari** [comment] 2015-05-05 14:40
hi :) 
i'm using das-quadrat in my app 
the problem that i've faced that when i change my location a little bit no new venue appear :S 
new venues appear only if the change in location vast 
anyone faced the same problem ?
any suggestion for solution ? 
thanks
